source 'https://github.com/CocoaPods/Specs.git'

target 'FancyShop' do
  use_frameworks!
  platform :ios, '11.0'

  # Pods for MerchantApp
  pod 'MCSCommerceWeb', :podspec => '../../MCSCommerceWeb.podspec'

  pod 'Alamofire' ,'4.9.1'
  pod 'SDWebImage','5.4.2'
  pod 'NVActivityIndicatorView','4.8.0'
end
